sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VZE6rbkKw/KgGPcTQMsj+EpGtfN66xRjajJ5t0ssIuCCMWBZx6/kLOVenuBNPEfDML0EnKmZ1OG4SmA07yiwNgXSDiNbq/+YrC+QCXX5KGvG1q7zxzT3IC/ds0YGt1VWHDFviFYVq7rMhoDqX98Uj+kCg01guUJv+SIF4J5lg7iIBl2vaJj0dUGw1ZlwgHnHkmI1apui2UOfUb9A4krM0t9OYHSY0pB7c7vBTAU0YKeDaoJc84ef89DvUo82WVadX06wrtuuBmgg7VIq6z7yf8pXpoy6tYJbk1qJobkbZi6k7GC9cFLq13V8j+4Um/Rh/vFCSy+4v/wWboAXQMYx5+F3Qt9ALGY63XGN2AbPYAzRuVmuMxf4L3uqK8uqEBBPAK366vD8whkji/ZOI/NzOewiuFBjqzxg2g0kLd1au98BRLFLUqTxsyRmQYRw0dqrxuQYPmj5YttVV6HEiwQfeEAGyWnHUaGeeaNv5ScBrAMTST56jiLEgjkPLKk7cWWKaPzEiE/2GuttAQKNli0AfLhBIxWHciptJmH1zTlKEjVNHcIylIOMvL05eEe5TnRYvtC2YBLqyMpaxzxYkA6e1idxRLTh/DdReBGkYoDkLc0fa+w+XsNP3Fys8xYIrBDMfb5G1zWViqPql9IPJN3jCdXrnH77/w7fVqwV0CiG9gc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Cleopatra---Complete_5482
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy